name: Deployment Workflow
on:
  push:
    branches: [ master ]

jobs:
  CD:
    name: Continuous Delivery
    runs-on: ubuntu-latest
    steps:
      - name: SSH into production server
        uses: appleboy/ssh-action@master
        with:
          port: 22
          username: root
          host: ${{secrets.HOST}}
          key: ${{secrets.PRIVATE_KEY}}
          script: |
            cd /root/sites/MiHorarioWeb
            git pull origin master
            git status
            npm i
            npm run build
            pm2 restart server
