name: Deployment Workflow
on:
  push:
    branches: [ master ]

jobs:
  CD:
    name: Continuous Delivery
    runs-on: ubuntu-latest
    steps:
      - name: SSH into production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: ${{secrets.PORT}}
          script: |
            cd /root/MiHorarioWeb
            git pull origin master
            git status
            /usr/bin/npm i
            /usr/bin/npm run build
            /usr/bin/pm2 restart server